### ISSUE TITLE
SalesLoft Cog: Custom fields are not being handled.

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-salesloft#4]
1. Open cmd
2. Type in crank cog:steps automatoninc/salesloft
3. Add the "Create or updat a salesloft person step"
4. Add the "Check a field on a SalesLoft person"
5. Aside from email_address field, make sure to add any custom field (NicksTest123)
6. Run the scenario.

![image](https://user-images.githubusercontent.com/54615569/65856151-670b4400-e393-11e9-98d2-d1375f4aaacb.png)

**Comment by amcpanaligan** [comment]
So far, the only handled scenario is `validating` the `custom_field` of a salesloft person. However, we cannot still create a `person` with any `custom_field`
